name: 'Terraform'

on:
  push:
    branches:
      - main
    paths:
      - 'bigquery/views/*.sql'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'bigquery/views/*.sql'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch minimal history for comparison

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Get list of changed SQL files
        id: changed-files
        run: |
          # Determine the base commit to compare against
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_COMMIT="${{ github.base_ref }}"
            HEAD_COMMIT="${{ github.head_ref }}"
          else
            BASE_COMMIT="HEAD~1"
            HEAD_COMMIT="${{ github.sha }}"
          fi

          # Perform the git diff to find changed .sql files
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT $HEAD_COMMIT -- bigquery/views/*.sql)

          if [ -z "$CHANGED_FILES" ]; then
            echo "No SQL files changed."
            echo "FILES_CHANGED=false" >> $GITHUB_ENV
          else
            echo "SQL files changed: $CHANGED_FILES"
            echo "FILES_CHANGED=true" >> $GITHUB_ENV
          fi
      
      - name: Terraform Plan if any .sql files changed
        if: env.FILES_CHANGED == 'true'
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply if any .sql files changed
        if: env.FILES_CHANGED == 'true' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
